In [1]:
import numpy as np
from keras.datasets import mnist
import keras
from keras import layers
from sklearn.metrics import classification_report, confusion_matrix

### Wczytanie i konwersja danych

In [2]:
training_set, test_set = mnist.load_data()

In [3]:
X_train, y_train = training_set
X_test, y_test = test_set

In [4]:
print(X_train.shape)

(60000, 28, 28)


In [5]:
X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)

In [6]:
print(X_train.shape)

(60000, 28, 28, 1)


In [7]:
X_train = X_train.astype(float) / 255.0  
X_test = X_test.astype(float) / 255.0

### Przygotowanie eksperymentu

In [8]:
num_classes = 10
input_shape = (28, 28, 1)
batch_size = 128
epochs = 40

In [9]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 10)                7850      
                                                                 
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

### Uczenie modelu

In [12]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/40
375/375 [==============================] - 1s 2ms/step - loss: 0.7593 - accuracy: 0.8122 - val_loss: 0.4132 - val_accuracy: 0.8959
Epoch 2/40
375/375 [==============================] - 1s 2ms/step - loss: 0.3931 - accuracy: 0.8953 - val_loss: 0.3367 - val_accuracy: 0.9125
Epoch 3/40
375/375 [==============================] - 1s 2ms/step - loss: 0.3407 - accuracy: 0.9074 - val_loss: 0.3080 - val_accuracy: 0.9158
Epoch 4/40
375/375 [==============================] - 1s 2ms/step - loss: 0.3160 - accuracy: 0.9126 - val_loss: 0.2969 - val_accuracy: 0.9183
Epoch 5/40
375/375 [==============================] - 1s 2ms/step - loss: 0.3014 - accuracy: 0.9160 - val_loss: 0.2851 - val_accuracy: 0.9204
Epoch 6/40
375/375 [==============================] - 1s 2ms/step - loss: 0.2915 - accuracy: 0.9187 - val_loss: 0.2778 - val_accuracy: 0.9224
Epoch 7/40
375/375 [==============================] - 1s 2ms/step - loss: 0.2842 - accuracy: 0.9208 - val_loss: 0.2737 - val_accuracy: 0.9247
Epoch 

### Ocena modelu

In [13]:
from sklearn.metrics import classification_report, confusion_matrix

In [14]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

313/313 [==============================] - 0s 1ms/step


In [15]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.98      0.97       980
           1       0.97      0.98      0.98      1135
           2       0.93      0.90      0.92      1032
           3       0.91      0.91      0.91      1010
           4       0.95      0.93      0.94       982
           5       0.91      0.87      0.89       892
           6       0.94      0.95      0.95       958
           7       0.94      0.92      0.93      1028
           8       0.88      0.90      0.89       974
           9       0.90      0.93      0.91      1009

    accuracy                           0.93     10000
   macro avg       0.93      0.93      0.93     10000
weighted avg       0.93      0.93      0.93     10000

[[ 960    0    0    2    1    7    7    2    1    0]
 [   0 1114    3    3    0    1    3    2    9    0]
 [   4    9  932   16    6    3   14   10   35    3]
 [   3    0   19  918    0   24    2   11   24    9]
 [   1    1    7    1  909   

### Uczenie modeli nieliniowych
#### a)

In [16]:
num_classes = 10
input_shape = (28, 28, 1)
batch_size = 128
epochs = 30

model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(64, activation="tanh"),
            layers.Dense(128, activation="tanh"),
            layers.Dense(num_classes, activation="softmax")
        ]
    )
model.summary()
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_1 (Dense)             (None, 64)                50240     
                                                                 
 dense_2 (Dense)             (None, 128)               8320      
                                                                 
 dense_3 (Dense)             (None, 10)                1290      
                                                                 
Total params: 59,850
Trainable params: 59,850
Non-trainable params: 0
_________________________________________________________________
Epoch 1/30
375/375 [==============================] - 1s 3ms/step - loss: 0.4134 - accuracy: 0.8841 - val_loss: 0.2231 - val_accuracy: 0.9366
Epoch 2/30
375/375 [====================

#### b)

In [17]:
num_classes = 10
input_shape = (28, 28, 1)
batch_size = 128
epochs = 30

model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Flatten(),
            layers.Dropout(0.5),
            layers.Dense(num_classes, activation="softmax"),
        ]
    )
model.summary()
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 flatten_2 (Flatten)         (None, 1600)              0         
                                                                 
 dropout (Dropout)           (None, 1600)             